### ISSUE TITLE
Couldn't get updated image object when use pesdk ReactComponent

### ISSUE THREAD

**Issue by JavascriptNinja815** [imgly/pesdk-react-demo#5]
Is there any way that able to get updated image object using ReactComponent? (i.e. i'd like to get image object when click export button)

If yes, what props/method should i use? (i couldn't find any such info in documentation)

**Comment by NadimD** [comment]
Bump, I second that question, I can't seem to bind a "on" event on export.
Accessing the editor.ui isn't enough to make events.
Have you found a solution ?

**Comment by NadimD** [comment]
Hello,

I've found the way to set an event on export.

First of all, when using PESDK in React, let's imagine you're based on this demo.

You have a ReactComponent, I added some options for you to see how it works : 

`<ReactComponent
              ref={this.photoEditorSDK}
              license='my_license_here'
              assets={{
                  baseUrl: './node_modules/photoeditorsdk/assets'
              }}
              editor={{
                  image: this.props.image,
                  tools: ['transform', 'filter', 'brightness', 'saturation', 'contrast', 'exposure', 'shadows', 'highlights', 'gamma', 'text'],
                  export: {
                      format: 'image/png',
                      type: 'data-url',
                      download: false,
                  }
              }}
              enableWebcam={false}
              enableUpload={false}
              showCloseButton={false}
              style={{
                  width: "100%",
                  height: 576
              }}
              />`

See the `ref={this.photoEditorSDK}` ?

Now register this ref in the constructor : 

`this.photoEditorSDK = React.createRef();`

Now let's imagine you want to bind and event on export, you can't actually do it in the constructor because the component don't exists yet. So you'll have to create a method like eventHandler, clickHandler, whatever you want, and call your ref with the following syntax, accessing all of its sub methods. Some examples below : 

```
// Custom method in the same component
resetEditor(e){
        // Empty the image
        return this.photoEditorSDK.current.ui.setImage(new Image());
}
```

```
bindExportEvent(){
        this.photoEditorSDK.current.ui.on('export', (result) => {
            console.log('exported' + result);
        });
}
```

Note that according to the documentation ( https://docs.photoeditorsdk.com/apidocs/html5/v4/PhotoEditorSDK.UI.ReactUI.html ), `ui` extends `EventEmitter`, which has all the methods related to the events (on, off, once, etc) : 
https://docs.photoeditorsdk.com/apidocs/html5/v4/PhotoEditorSDK.EventEmitter.html

**Comment by JavascriptNinja815** [comment]
Thanks for your help, NadimD.

**Comment by AndyNeale** [comment]
Excellent work, NadimD, that's saved me a whole lot of time and frustration! It's a shame the official documentation isn't this comprehensive...

**Comment by keiwando** [comment]
It seems like the `ui` property of the ReactComponent was not documented for some reason. I fixed that to make sure that it shows up in our API docs and added the respective examples for registering event callbacks and accessing the SDK functions to the README here.

Thanks @NadimD for providing this detailed explanation as well.
